import Vue from 'vue'
import ElementUI from 'element-ui'
import lodash from 'lodash'
import Icon from 'vue-awesome/components/Icon.vue'
// import webix from 'webix'
import Vuex from 'vuex'
// import 'webix/webix.css'
import Vapi from 'vuex-rest-api'
import moment from 'moment'
import VueMoment from 'vue-moment'
import axios from 'axios'
import VueMarkdown from 'vue-markdown'

import VueScrollTo from 'vue-scrollto'
